script: make ci
gemfile:
  - test/railsapi/Gemfile.rails_3_0
  - test/railsapi/Gemfile.rails_3_1
  - test/railsapi/Gemfile.rails_3_2
  - test/railsapi/Gemfile.rails_head
branches:
  only:
    - master
    - develop
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - rbx-19mode
before_install: gem install bundler --pre
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: test/railsapi/Gemfile.rails_3_0
    - rvm: 2.0.0
      gemfile: test/railsapi/Gemfile.rails_3_1
    - rvm: ruby-head
      gemfile: test/railsapi/Gemfile.rails_3_0
    - rvm: ruby-head
      gemfile: test/railsapi/Gemfile.rails_3_1
