script: make test
gemfile:
  - test/railsapi/Gemfile.rails_3_1
  - test/railsapi/Gemfile.rails_3_2
  - test/railsapi/Gemfile.rails_head
branches:
  only:
    - master
    - develop
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - rbx-19mode
  - ree
before_install: gem install bundler --pre
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: test/railsapi/Gemfile.rails_head
