services:
  - redis
script: make ci
gemfile:
  - test/railsapi/Gemfile.rails_3_2
  - test/railsapi/Gemfile.rails_head
branches:
  only:
    - master
    - develop
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
before_install:
  - gem install bundler --version '= 1.3.1'

